pipeline {
    agent { label 'agent_01' }

    options {
        skipDefaultCheckout(false)
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Info') {
            steps {
                sh 'hostname'
                sh 'whoami'
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('catalogue') {
                    sh 'npm install'
                }
            }
        }

        stage('Package') {
            steps {
                dir('catalogue') {
                    sh '''
                        rm -f catalogue.tar.gz
                        tar -czf catalogue.tar.gz Jenkinsfile README.md db node_modules package-lock.json package.json server.js
                        ls -lh catalogue.tar.gz
                    '''
                }
            }
        }
    }
}